export const ROLES = Object.freeze({
  SUPER_ADMIN: "SUPER_ADMIN",
  BRANCH_ADMIN: "BRANCH_ADMIN",
  ECCLESIA_LEADER: "ECCLESIA_LEADER",
  FINANCE_ADMIN: "FINANCE_ADMIN",
});

export const ROLE_VALUES = [
  ROLES.SUPER_ADMIN,
  ROLES.BRANCH_ADMIN,
  ROLES.ECCLESIA_LEADER,
  ROLES.FINANCE_ADMIN,
];
