export const FINANCE_TRANSACTION_TYPES = [
  "TITHE",
  "SUNDAY_OFFERING",
  "BUSCELL_OFFERING",
  "WELFARE",
  "PLEDGE",
];

export const FINANCE_PAYMENT_METHODS = ["CASH", "MOMO", "CARD", "TRANSFER"];
